name: Code check

on:   
  push:
    branches: [ main ]
    paths-ignore:
      - .github/**
      - charts/**
      - config/**
      - docs/**
      - hack/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - .github/**
      - charts/**
      - config/**
      - docs/**
      - hack/**

jobs:

  gofmt:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Run go fmt
      run: d="$(gofmt -d ../../)" && if [ -n "$d" ]; then echo "format error:" ; echo "$d"; exit 1; fi      

  check-crd:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Recreate crd
      run: make manifests

    - name: Check crd
      run: diff charts/mysql-operator/crds config/crd/bases

  staticcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@2020.2.1

    - name: Run staticcheck
      run: staticcheck -f stylish ./... 
